### ISSUE TITLE
Feature Request: Publish releases on f-droid.org

### ISSUE THREAD

**Issue by Boruch-Baum** [thomasokken/free42#11]
f-droid.org is a (popular?) 'free' apk store alternative to google. The convenience of it to users is that new releases can be automatically updated instead of tracking each developer's website and manually side-loading.

**Comment by thomasokken** [comment]
If anyone wants to add Free42 to the f-droid repository, I'll be happy to help getting that set up, but I am not prepared to deal with this on an ongoing basis. For people who are looking to receive automatic notifications when Free42 is updated, I recommend using a web site monitoring service (google "check website changes" to find several) and have it monitor the Free42 home page, the project history page, or the Free42Android.apk file itself.

**Comment by Boruch-Baum** [comment]
At first glance, it doesn't seem they ask for any help from either of us, so I've submitted a request here: https://gitlab.com/fdroid/rfp/-/issues/1448

**Comment by thomasokken** [comment]
The fdroid scanner's report includes the following:

versionCode: 125
Errors
* Java JAR file: android/app/libs/android-support-v4.jar
* gzip file archive: inteldecimal/IntelRDFPMathLib20U1.tar.gz

If I understand this correctly, fixing these errors would require creating a downstream repository in which the android-support-v4.jar is built from source, and in which the Intel library is checked in as individual files rather than as a tarball.
In addition, the gradle file would probably have to be modified to run the link-files.sh and build-intel-lib.sh scripts in android/app/src/main/cpp. (In my production builds, this is handled by the top-level build-android script.) There may be further issues, depending on how tolerant f-droid is of builds that require shell scripts instead of doing everything in gradle.

**Comment by Boruch-Baum** [comment]
On 2020-08-15 07:16, Thomas Okken wrote:
>    The fdroid scanner's report includes the following:
>
>    versionCode: 125
>    Errors
>      * Java JAR file: android/app/libs/android-support-v4.jar
>      * gzip file archive: inteldecimal/IntelRDFPMathLib20U1.tar.gz
>
>    If I understand this correctly, fixing these errors would require
>    ...

I'm no f-droid expert, but I wouldn't jump the gun because an automated
test raised that kind of error, that is unless you know already that you
don't support Android v4 and you want to. To me, it doesn't seem right that
f-droid would reject a submission for that kind of incompatibility. I
vote to wait for some kind of follow-up message that seems to be from a
 sentient life-form.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by IzzySoft** [comment]
Confirming the analysis of @thomasokken: F-Droid doesn't accept binaries, all must be built from source. Especially JAR/AAR files, `.so` etc are regular deal-breakers. The Tar file's contents could also be included as git sub-module if you prefer. And if the JAR is available in one of the [trusted maven repos](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L104), it could be included via that.

<sup>Disclosure: sentient life-form, type: F-Droid maintainer :wink:</sup>

**Comment by Boruch-Baum** [comment]
@IzzySoft: Thanks for the head-up. Sorry that I'm not the guy for this job, so I apologize for the fuss caused. I meant well; I thought this would be a great up-to-date addition for the f-droid collection and didn't think adding it would involve major work.

**Comment by IzzySoft** [comment]
@Boruch-Baum no harm done, this is a frequent issue. If @thomasokken is willing to do the "reorg", we can add the app to F-Droid. If he doesn't want, no bad feelings either but we'd have to close your request unfulfilled. It's always worth trying, keep it up!

**Comment by thomasokken** [comment]
If I'm reading [https://mvnrepository.com/artifact/com.android.support/support-v4/25.2.0] correctly, android-support-v4.jar could be retrieved from maven.google.com. Unzipping the Intel library tarball in the repo would also not be a big deal, although it would require changes to several build scripts. I think the biggest concern would be the android/app/src/main/cpp/build-intel-lib.sh script; this script patches the Intel sources and invokes the Intel build scripts, inserting wrapper scripts around the NDK's cc and ar. There are hard-coded dependencies on NDK details there as well. Making all that work in the f-droid build environment could be a bit of a challenge, and I won't have time for that any time soon.
