### ISSUE TITLE
Review and possible feature requests

### ISSUE THREAD

**Issue by jackokring** [thomasokken/free42#12]
https://kring.co.uk/2020/08/free42-android-app-longer-term/

I've used it for a while now and it's excellent. No criticism is due. Mainly a few new commands to help keep variable clutter down and allow easier programs which define operators or heavily nested iterative functions.

**Comment by jackokring** [comment]
https://github.com/jackokring/free42-1 first change of core_commads5.cc

**Comment by thomasokken** [comment]
LSTO (2.2) and FUNC (2.5.24) help a lot with variable clutter, and more changes are in the works which will also help. Stay tuned.
I'm closing this now but feel free to reopen after 3.0 is out if you feel new functionality is still needed then.
