### ISSUE TITLE
Suggest storing sigma x^2 y

### ISSUE THREAD

**Issue by jackokring** [thomasokken/free42#13]
Calculation of the weighted variance is a bit challenging without this stat. I suggest R24 in ALL-sigma mode.

**Comment by jackokring** [comment]
Somewhere down the page on https://kring.co.uk/2020/08/free42-android-app-longer-term/ a Q-Sigma mode is suggested for quadratic regression with a lin, log, exp and power overlay. It conveniently would fit in the 25 default REGS to be a saved state and maybe use flag 64 to enable it. It would be independent of the R24 idea as the weighted variance is a thing that should be easy, but can't be reconstructed with the register saved data.

**Comment by thomasokken** [comment]
Calculation of statistics and regression models outside of the capabilities of the HP-42S must be done using user code programs. I have no plans to add new stat functionality.
