### ISSUE TITLE
ARM support under Linux (armv7 and aarch64)

### ISSUE THREAD

**Issue by plabadens** [thomasokken/free42#14]
Hi there, I am currently trying to package Free42 for NixOS, a Linux distribution. It seems the build is failing on ARM systems, due to the Intel floating point library not building properly on these architectures (`armv7` and `aarch64`). I have attached build logs for both an x86_64 and an aarch64 system.

- Failure to build on aarch64, with message `makefile.iml_head:356: *** Unknown host architecture aarch64.  Stop.` from the Intel lib ([free42-aarch64-linux.log](https://github.com/thomasokken/free42/files/5474504/free42-aarch64-linux.log))
- Builds fine on x86_64 ([free42-x86_64-linux.log](https://github.com/thomasokken/free42/files/5474506/free42-x86_64-linux.log))

I can see that there are some patches that are applied to the Android build to fix the Intel library on these architectures, could these be included more generally to make Free42 portable to ARM systems? For now this is mostly relevant for Linux, but might include macOS in the future.

**Comment by plabadens** [comment]
After looking at this more closely, this is only relevant for systems that report their architecture as `aarch64`. See #15 for fix.

**Comment by thomasokken** [comment]
Merged. Thanks!
