### ISSUE TITLE
Feature Request: command line support

### ISSUE THREAD

**Issue by daitangio** [thomasokken/free42#16]
I am interested in a command line version, able to read & run program provided on standard input.
Can you drive me for this extension/modification?

**Comment by thomasokken** [comment]
I agree that a command-line version would be useful, but I haven't yet managed to come up with a design for the user interface for one. I'd have to have a workable idea for this before I can even consider implementing it.

**Comment by JensGrabner** [comment]
I use these here: https://www.chiark.greenend.org.uk/~sgtatham/spigot/

**Comment by thomasokken** [comment]
The devil is in the details. Could you give some examples of what an interaction with a hypothetical command-line Free42 would actually look like? In interactive use, and invoked from a script?

**Comment by daitangio** [comment]
Let me give some ideas. We can provide a command line interface which works in this way:

1. It reads on standard input an HP42S Program
2. After a"END" is hit,  it start executing the first program called "AUTOBOOT" if any.  Otherwise proceed reading data. In this way you can read a set of programs which can call each other. 
3. Printing commands will provide output on standard output. We can consider also to output "VIEW" / "AVIEW" command but printing API is more precise and can also print out programs and so on

The (2) can be simplified to start executing at the end of the input the first program, but I'd like to provide a "straming" service if possible, to interact with a command line pipe.
Limitations:

No graphics
No sound

How it is difficult to create a interface of this kind?
