### ISSUE TITLE
Feature request: adaptive icon for Android 8 and up

### ISSUE THREAD

**Issue by johanw666** [thomasokken/free42#18]
The current Free42 icon on Android 8 and higher is too small, see the added screenshots:

![free42_icon](https://user-images.githubusercontent.com/8427572/103320396-7618f000-4a35-11eb-873c-12391dc480db.jpg)

In Android 8 adaptive icons were introduced, so they fill better, like WhatsApp uses:

![whatsapp_icon](https://user-images.githubusercontent.com/8427572/103320426-9779dc00-4a35-11eb-9b8f-a24947ace22a.jpg)

The procedure to add an adaptive icon in Android is easy in Android Studio, the procedure is described here: https://dev.to/sfarias051/how-to-create-adaptive-icons-for-android-using-android-studio-459h

I would like to create a pull request with the changes, but the larger icon in the util/icons folder needs to be scaled and I can't build Free42 on windows to test how it looks like on a real device. I could build a test project with this icon and copy the parameters to a PR for Free42 if you like though.

**Comment by thomasokken** [comment]
Sure, I'd like to take a look at that! I agree the Android icon could do with being a bit larger.
If you have a util/icons folder, your source may be a bit out of date. I keep the icons in https://github.com/thomasokken/free42util now. The icons in the release versions were based on icon-2200x2200-lighter.png and icon-2200x2200-transparent-lighter.png.

**Comment by thomasokken** [comment]
I don't have a physical device at hand at the moment, either. I'm on vacation at the moment and I left my Android phone at home. I won't be able to test with that until next week. I am able to run builds and test in the emulator, though.

**Comment by johanw666** [comment]
I took the icons from a zipfile from the 2.5.16 source. I'll build a test project with just this icon to see how it scales, then make a pull request with those settings and upload both so you can check. I can't checkif my changes will build though, I hope they do.
