### ISSUE TITLE
[android] auto-rotate doesn't change skin on Android 11

### ISSUE THREAD

**Issue by aswild** [thomasokken/free42#19]
Ever since upgrading from Android 10 to 11, Free42 doesn't switch skins when rotating the screen, instead the portrait skin gets squished to landscape dimensions. This isn't an issue in Android 10.

Emulator screenshot:
![image](https://user-images.githubusercontent.com/11742669/104823857-39ae0800-581b-11eb-8ec7-72a2c0c46b65.png)

Changing the skin manually works, but then the reverse problem happens when switching back to portrait mode.

Fortunately, it seems like there's an easy fix. According to https://developer.android.com/guide/topics/resources/runtime-changes

 > If you want to manually handle orientation changes in your app you must declare the "orientation", "screenSize", and "screenLayout" values in the android:configChanges

Free42's manifest only specifies `android:configChanges="orientation"`, and changing that to `android:configChanges="orientation|screenSize|screenLayout"` seems to work for me and restore the expected skin-switching behavior.

I'm not sure why screenSize and screenLayout are required when Free42Activity's onConfigurationChanged method only cares about orientation, and the docs don't mention any changes between Android 10 or 11.

**Comment by thomasokken** [comment]
Interesting! What exactly is failing with configChanges="orientation"? Is the onConfigurationChanged handler not called at all, or is it called but is the OS lying about the screen geometry?

**Comment by thomasokken** [comment]
Ah, never mind, you seem to be getting this behavior in the Android Emulator, so I should be able to reproduce it and look into it myself. I'll probably end up adopting your fix but I'd like to take a look at what exactly is happening first.

**Comment by thomasokken** [comment]
Trying the Android 10 emulator first, it looks like an even bigger train wreck. The screen gets mangled badly, and the onConfigurationChanged callback is never called at all, not even when I set configChanges="orientation|screenSize|screenLayout". I wonder, is it just the Android Emulator that is broken with respect to orientation changes? This is weird because I know I have tested this functionality in the emulator at some point, but it was probably a long time ago...
![Screen Shot 2021-01-16 at 7 27 55 PM](https://user-images.githubusercontent.com/17934252/104827906-46d5f180-5831-11eb-8d0b-f7393b950923.png)

**Comment by thomasokken** [comment]
When I force the orientation change in the app, by setting Orientation to Landscape in the Preferences, it does work fine, with either value of configChanges. Confusing! Why does that work, while the emulated hardware orientation change is such a mess?
Trying the Android 11 emulator tomorrow...

**Comment by aswild** [comment]
I had the same experience with my real phone (Pixel 3, stock ROMs), the emulator was just easier to screenshot. In the emulator I'm using the x86_64 Google Play system images (and the latest Android Studio & emulator on Linux).

I added a log message at the beginning of onConfigurationChanged and I see that:
 * when `configChanges="orientation"`, onConfigurationChanged gets called on 10 but not on 11
 * when using `configChanges="orientation|screenSize|screenLayout"`, onConfigurationChanged gets called on both 10 and 11.

Maybe there's weird emulator version differences or something Mac vs Linux going on, that's definitely weird.

I also found this comment in the manifest documentation https://developer.android.com/guide/topics/manifest/activity-element#config

> Note: If your application targets Android 3.2 (API level 13) or higher, then you should also declare the "screenSize" and "screenLayout" configurations, because they might also change when a device switches between portrait and landscape orientations.

**Comment by thomasokken** [comment]
With the Android 11 emulator (x86), I don't get the mangled screen, but onConfigurationChanged isn't getting called at all, neither with configChanges="orientation" nor with configChanges="orientation|screenSize|screenLayout". The orientation change appear to be getting completely ignored.

![Screen Shot 2021-01-16 at 10 23 47 PM](https://user-images.githubusercontent.com/17934252/104830134-d5566d00-5849-11eb-9e64-f8fbccde21a8.png)

**Comment by thomasokken** [comment]
Aha! Looking more closely, when I turn the phone sideways, there is a pair of rotating arrows in the bottom right corner for a few seconds. When I tap on that, the onConfigurationChanged callback is called and the orientation change is handled. And, as you described, the skin switch happens with configChanges="orientation|screenSize|screenLayout", and not with configChanges="orientation".

Interesting UI change, having to confirm the orientation change, but regardless, the change to configChanges looks like the right thing to do, so I'll make that change in master in a minute.

**Comment by thomasokken** [comment]
Done, built, and published.
Thank you for the report!
