### ISSUE TITLE
Any thoughts on a web version?

### ISSUE THREAD

**Issue by BigEd** [thomasokken/free42#22]
Perhaps, using emscripten?  Some example projects here
https://github.com/emscripten-core/emscripten/wiki/Porting-Examples-and-Demos#emulators

**Comment by thomasokken** [comment]
I'm not interested in doing that. It doesn't seem very useful.
Someone else has been working on such a port for a while, but there hasn't been any activity recently:
https://github.com/wginolas/free42

**Comment by BigEd** [comment]
Understood - thanks for the pointer
