### ISSUE TITLE
Only one version shows in Launchpad on macOS

### ISSUE THREAD

**Issue by Aaron-Rumpler** [thomasokken/free42#29]
When both Decimal and Binary versions are installed on macOS, only one version shows in the Launchpad. I believe this is due to both versions sharing the same bundle identifier.

**Comment by thomasokken** [comment]
Yes, I suppose so. Is that a problem, though? You **can** put both in the Dock.

**Comment by thomasokken** [comment]
Hmm, you know what, disregard that question. I'll see if I can build the two configurations with different bundle IDs. I may have to change the project a bit to do that, but apart from that, I don't think there is any reason **not** to make that change.

**Comment by thomasokken** [comment]
1ce9973df6797ec3e52397b3ca3e104b96d2c46e
