### ISSUE TITLE
Converting README to markdown

### ISSUE THREAD

**Issue by rogersachan** [thomasokken/free42#3]
If I did a pull request for this would it be accepted? Are there any build steps that expect the README to be in the text format?

**Comment by thomasokken** [comment]
None of the builds use the top-level README, so it could be any format whatsoever, but what would changing it to markdown accomplish?

**Comment by rogersachan** [comment]
It's mainly for people who find this repo through the github explore function or other means before they hit the homepage. From the github page, markdown is more readable than the existing text formatting that github uses.

**Comment by thomasokken** [comment]
It would be nice if it would use a slightly larger font! But other than that, I'm not sure. What I like about plain text is that it's readable whether you're looking at it on a web site or in a text editor or whatever.
