### ISSUE TITLE
How to copy skins to iPhone

### ISSUE THREAD

**Issue by ahlstromcj** [thomasokken/free42#35]
I have a collection of skin, including yours and mine, at https://github.com/ahlstromcj/free42-resources and will be getting an iPhone soon (after having an Android for years).  Is there any documentation on where to put the skins on and iPhone and how to get them there?

**Comment by thomasokken** [comment]
Free42 for iOS expects skins in the "skins" directory. You can put them there using the built-in HTTP server or using the Files app, but I think the easiest way is to use the built-in skin loader: Main Menu -> Select Skin -> Load..., then change the URL to the one where your collection is, and tap Go. You can then load skins the usual way, i.e. select a skin's gif or layout file and pressing Load. (You can choose either file; the other file will be loaded as well.)
