### ISSUE TITLE
Feature request: Option to bottom align skin on phones

### ISSUE THREAD

**Issue by thierer** [thomasokken/free42#36]
I would appreciate an option to bottom align the skin on phones (in my case Android) when "Maintain skin aspect ratio" is selected.

Having the skin vertically centered makes it imho unnecessarily difficult to operate the calculator with one hand, especially given the usually wide aspect ratio of modern phones.

**Comment by thomasokken** [comment]
Good idea. I keep hoping someone will contribute a patch for completely unconstrained skin scaling and positioning, that would be useful, especially on really large phones and on tablets! It's probably not that hard, but still hasn't made it to the top of my priority list...

**Comment by thomasokken** [comment]
I can't say when I'll get around to this. I'm putting it on my private to-do list and closing this issue for the time being.
