### ISSUE TITLE
Feature Request: Default stack mode for programs

### ISSUE THREAD

**Issue by Aaron-Rumpler** [thomasokken/free42#39]
When 'Allow Big Stack' is enabled, allow the user to set a default stack mode for programs. When a program is run, if it doesn't start with `L4STK` or `LNSTK`, the appropriate `LxSTK` for the default stack mode is run. This would allow the user to use either `4STK` or `NSTK` mode while retaining a single default mode for programs that don't use `LxSTK` (for example to retain compatibility with programs that expect a 4 level stack without having to manually add a `L4STK` to them).

**Comment by thomasokken** [comment]
I like the idea, but I can't say when I'll get around to this. I'm putting it on my private to-do list and closing this issue for the time being.
