### ISSUE TITLE
Feature Request: Allow L4STK when "Allow Big Stack mode" is disabled

### ISSUE THREAD

**Issue by Aaron-Rumpler** [thomasokken/free42#40]
Allow programs to use `L4STK` when "Allow Big Stack mode" is disabled. This would allow programs expecting a 4 level stack to begin with `L4STK` and run whether the calculator has "Allow Big Stack mode" enabled or not. This would also align with the current behaviour of allowing `4STK` when "Allow Big Stack mode" is disabled.

**Comment by Aaron-Rumpler** [comment]
Also, if `DEPTH`, `DROP`, `DROPN`, `DUP`, `DUPN`, `R↓N`, `R↑N`, `PICK`, and `UNPICK` work in `4STK` mode, why can they only be used when big stack mode is enabled?

**Comment by thomasokken** [comment]
I think you're confusing "Allow Big Stack (NSTK)" mode in Preferences and the 4STK/NSTK setting in MODES.

The former can be used to completely block all big stack functionality, and exists for people who want HP-42S compatibility, and don't want to risk accidentally turning on NSTK mode.

The latter is the one that actually switches between the 4-level and the N-level stack.

Everything you're requesting here already works, provided you have Allow Big Stack mode turned on.

**Comment by Aaron-Rumpler** [comment]
Sorry, I phrased that rather poorly. I've edited it to make it clearer.

**Comment by thomasokken** [comment]
Ah, OK. Yes, that makes sense.
I'll make the change, it will be in the next release.

**Comment by thomasokken** [comment]
d1fc266aa820d9be2e1ab52bff748a6a206f1d6f
