### ISSUE TITLE
No permission to access files while importing programs

### ISSUE THREAD

**Issue by quinvirE** [thomasokken/free42#49]
Not able to import programs because of insufficient permissions on Android 12 (LineageOS 19.1). App permissions are set to access media files only. RAW files are not visible in the in-app browser.

App version: 3.0.14

![Screenshot_20220901-145020_Free42](https://user-images.githubusercontent.com/112632772/187920409-13cd4948-254f-4fe8-aa49-006062778205.png)
![Screenshot_20220901-145053_Permission controller](https://user-images.githubusercontent.com/112632772/187920413-5b753a89-9d7d-42b1-afe7-38f22fa4071a.png)
![Screenshot_20220901-145008_Free42](https://user-images.githubusercontent.com/112632772/187920415-c277ab12-0142-4ce8-a0a8-0bbf2328fdb6.png)

**Comment by quinvirE** [comment]
Solved it by using Permission Manager X from F-droid

**Comment by sbridger** [comment]
Is this not a fault in the manifest for the program that needs fixing so that it has permission?
