### ISSUE TITLE
Printing from Android with IR blaster

### ISSUE THREAD

**Issue by maciozo** [thomasokken/free42#5]
Hello there,

Do you think it would be possible to implement printing with the IR blaster on some Android devices (such as some LG phones)? I don't have a printer myself, but I thought that this would be a rather cool (albeit of limited necessity) feature for those that do.

**Comment by thomasokken** [comment]
Whether it's possible or not depends on whether the LED can be controlled with enough precision or not. The protocol for talking to the HP-82240A/B printers is documented, and third-party implementations do exist.
I'm not interested in implementing this in Free42, though.
