### ISSUE TITLE
Extra button rows

### ISSUE THREAD

**Issue by sbridger** [thomasokken/free42#52]
On mobile phones the screen is longer. Stupidly so on my Sony X10III at 21:9.

It would be nice to have buttons for programs I would use all the time, and use up some of that dead space.

**Comment by thomasokken** [comment]
Plus42 does a pretty decent job of using that additional screen length. 😁
If you'd rather keep using Free42, you could create a skin with more keys, or use or modify an existing one... But with a customized skin, the key assignments for the extra keys are going to be hard-coded in the skin layout. Full keyboard customization, where you can assign any function or program to any key, is on my to-do list, but that's a long list and I don't consider this a high-priority feature, so realistically, I'd have to recommend against holding your breath on that one...
