### ISSUE TITLE
Complex number mode indicator

### ISSUE THREAD

**Issue by sbridger** [thomasokken/free42#57]
I am using complex numbers a lot at the moment.
You must know if you are in polar or rectangular _before_ you enter a complex number. 
When you are going back and forth, this is a constant problem: either you enter the number and the mode is wrong or you have to check the mode before entering a new number.

There should be an indicator showing the current mode on the top status line. This would be a big help

(this could be either the word rect/polar or if a smaller symbol is preferred, i/[anglesymbol] )

**Comment by thomasokken** [comment]
I am adding a polar indicator in the next Plus42 release. It will be shown in the header line.
Adding an annunciator is a different story. There are more than 100 skins already, and a new annunciator would have to be added to every one. That's a non-starter as far as I'm concerned.

**Comment by sbridger** [comment]
Do you know if there is a (programmatic) way to turn on the indicators? 
I have never used GRAD, print or beep in 35 years, and I can do this on my real '42

I would be happy to edit some skins to add two new annunciators. It is no issue if a skin doesn't have them, as that's the status quo anyway, no one will notice.

**Comment by sbridger** [comment]
As I was editing a couple of skins I use, I added Annunciators 8,9 in case you want to add...

http://i2cchip.com/free42/skins/
