### ISSUE TITLE
Beep and Beep Annunciator

### ISSUE THREAD

**Issue by sbridger** [thomasokken/free42#59]
(I don't use these, so I'm not actually requesting a fix. I only noticed this looking at the annunciators)

The Beep annunciator does not display on my Free42 Linux, Win, or android (on SFOS 4.5)

My android (on SFOS 4.5) does not make any noise when beep is operated.

**Comment by thomasokken** [comment]
In the Android and iOS versions, the TONE, BEEP, and error sounds are played as "system sounds," and those are governed by the same volume setting as the ringer, including being completely muted if the phone is set to silent.

As far as the (﹙·﹚) annunciator is concerned: I've never thought of it as the "beep" annunciator; to me, it was always the "running" annunciator. Free42 only turns it on when a program is running.

**Comment by sbridger** [comment]
Didn't occur to me that was what it is for!
Do you know if there is a (programmatic) way to turn on the an annunciator?

**Comment by thomasokken** [comment]
Well, like I said, it's on when a program is running.
