### ISSUE TITLE
MENU KEY 7/8 & Annunciators

### ISSUE THREAD

**Issue by sbridger** [thomasokken/free42#60]
OK, dragged my actual paper HP42 manual out, and found CLMENU

------

The up/dn annunciator is always on when I have a MENU
This may be because the KEY N xxx yyyy  menu is persistent i.e. if I run MENU again with no KEY commands. it will bring up the previous KEY items.

You [say that Free42 enables them when KEY 7 or KEY 8 is used](https://www.hpmuseum.org/forum/thread-6835.html?highlight=annunciators)
So either the annunciator is always on and the above is incorrect, or (more likely), I am unable to clear a previously set KEY 7 or KEY 8 menu item. 

Is there a way to clear these KEY N menu items?

---
As an aside my complex number menu is type sensitive**. Unfortunately this requires an event to be fired anytime the contents of X changes to update the menu. This is pretty much any key being pressed. While I have yet to think it through, an any key: KEY 10 might be a way to do it.

**i.e. the menu changes according to X being real, rect complex or polar complex. As soon as you press a number key, it becomes a real number again.
So I am testing CPX? and flag 73 (polar)

**Comment by sbridger** [comment]
also while editing a couple of skins I added RECT and POLAR annunciators 8,9
http://i2cchip.com/free42/skins/

**Comment by thomasokken** [comment]
> Is there a way to clear these KEY N menu items?

CLMENU

(Only replying to this one question right now -- I'll reply to the others later.)
