### ISSUE TITLE
Menu does not work when using Tyge_S2_Landscape skin

### ISSUE THREAD

**Issue by johanw666** [thomasokken/free42#7]
When I download and select the Tyge_S2_Landscape skin, the menu does not show anymore after tapping on the screen. Instead, the symbol for orange shift is shown on the screen. That also means I can not select another skin.

When I go to the apps data directory and remove the files manually (my device is rooted) it automatically selects a standard skin where this does work. But for a non-root user  the only way to fix it would be to remove all program settings.

Free42 Android 2.5.18

Devices tested on:
Samsung A2 tablet, Android 7.0
Sony Z3 Compact, Android 6.0.1

**Comment by thomasokken** [comment]
That skin maps a shift key on top of the top part of the display, and that interferes with the menu trigger. However, you should still be able to access the menu by tapping the skin above the display. It is a small area you have to hit, but I checked and it does work.

Thomas

**Comment by johanw666** [comment]
Thanks, I got it to work, I had not noticed that.
