### ISSUE TITLE
(feature request) GTK UI : show tooltips over buttons for shortcuts

### ISSUE THREAD

**Issue by fenugrec** [thomasokken/free42#72]
I see where the shortcuts are documented in this repo, but in the GTK build, they are not easily discoverable :

- no entry in Help menu (some programs have a "show key mappings" in there)
- not configurable in File->preferences (this is fine, not really a necessary feature IMO)
- no tooltips when hovering over a button. I think this would be a great improvement in usability.

Great program regardless, thanks !

**Comment by thomasokken** [comment]
The keyboard mappings are documented in the README file that's included in the download package. They can be customized by editing $HOME/.local/share/free42/keymap.txt.

**Comment by fenugrec** [comment]
Yes I understand that. Just suggesting that making that info easily accessible from the UI would be helpful.

**Comment by thomasokken** [comment]
I don't like the idea of using tooltips for this, but I could add an option to draw an overlay showing all the mappings at once. I'll put it on my to-do list.

**Comment by thomasokken** [comment]
Something like this:
(work in progress...)

<img width="340" alt="Screenshot 2024-12-09 at 15 47 10" src="https://github.com/user-attachments/assets/a4a36f97-c105-4598-80c1-90995ae43e1b">
