### ISSUE TITLE
Adding [MIN], [MAX] and [FIND] to catalog?

### ISSUE THREAD

**Issue by svillemot** [thomasokken/free42#9]
I suggest to add `[MIN]`, `[MAX]` and `[FIND]` to the catalog, along with the extensions that you made to the original HP-42S function set.

That would make it easier to key them in. Moreover, it would also remind the user that those functions exist.

Please forgive me if there is a good reason why this has not been done already, I’m quite new to the project.

**Comment by thomasokken** [comment]
The only reason they aren't in the FCN catalog in Free42 is that they aren't in the catalog in the real HP-42S, either. I agree they might as well be added, there isn't any real downside to doing so.

**Comment by thomasokken** [comment]
54ea4bb24b494c1a0d22e2e8836d896b8a27a418

**Comment by svillemot** [comment]
Thanks!
